<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE pedidos [
  <!ELEMENT pedidos (year*)>
  <!ELEMENT year (trimestre*)>
  <!ATTLIST year y CDATA #REQUIRED>
  <!ELEMENT trimestre (cliente*)>
  <!ATTLIST trimestre t CDATA #REQUIRED>
  <!ELEMENT cliente (nombre, apellidos, tlf, direccion, correo, fecha_inclusion, detalles_pedido)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT apellidos (#PCDATA)>
  <!ELEMENT tlf (#PCDATA)>
  <!ELEMENT direccion (calle, ciudad, cp, provincia)>
  <!ELEMENT calle (#PCDATA)>
  <!ELEMENT ciudad (#PCDATA)>
  <!ELEMENT cp (#PCDATA)>
  <!ELEMENT provincia (#PCDATA)>
  <!ELEMENT correo (#PCDATA)>
  <!ELEMENT fecha_inclusion (#PCDATA)>
  <!ELEMENT detalles_pedido (id_pedido, fecha_compra, fecha_entrega, total_factura, items)>
  <!ELEMENT id_pedido (#PCDATA)>
  <!ELEMENT fecha_compra (#PCDATA)>
  <!ELEMENT fecha_entrega (#PCDATA)>
  <!ELEMENT total_factura (#PCDATA)>
  <!ELEMENT items (nombre, referencia, precio, unidades)>
  <!ELEMENT referencia (#PCDATA)>
  <!ELEMENT precio (#PCDATA)>
  <!ELEMENT unidades (#PCDATA)>
]>

<pedidos>
    <year y="2021">
        <trimestre t ="1">
            <cliente>
                <nombre>Kara</nombre>
                <apellidos>Roose</apellidos>
                <tlf>865-212-0796</tlf>
                <direccion>
                    <calle>13779 Crescent Oaks Terrace</calle>
                    <ciudad>Knoxville</ciudad>
                    <cp>37919</cp>
                    <provincia>Tennessee</provincia>
                </direccion>
                <correo>iabarcae@yahoo.es</correo>
                <fecha_inclusion>08/07/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>01</id_pedido>
                    <fecha_compra>05/01/2021</fecha_compra>
                    <fecha_entrega>09/01/2021</fecha_entrega>
                    <total_factura>229,98€</total_factura>
                    <items>
                        <nombre>Nilait Prisma 40FA5001S 40" LED FullHD Smart TV</nombre>
                        <referencia>10464961</referencia>
                        <precio>229,98€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Kara</nombre>
                <apellidos>Roose</apellidos>
                <tlf>865-212-0796</tlf>
                <direccion>
                    <calle>13779 Crescent Oaks Terrace</calle>
                    <ciudad>Knoxville</ciudad>
                    <cp>37919</cp>
                    <provincia>Tennessee</provincia>
                </direccion>
                <correo>iabarcae@yahoo.es</correo>
                <fecha_inclusion>08/07/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>02</id_pedido>
                    <fecha_compra>12/01/2021</fecha_compra>
                    <fecha_entrega>18/01/2021</fecha_entrega>
                    <total_factura>425,99€</total_factura>
                    <items>
                        <nombre>Samsung HW-Q700B Barra de Sonido 3.1.2 Canales 320W Negra</nombre>
                        <referencia>10647263</referencia>
                        <precio>425,99€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Kara</nombre>
                <apellidos>Roose</apellidos>
                <tlf>865-212-0796</tlf>
                <direccion>
                    <calle>13779 Crescent Oaks Terrace</calle>
                    <ciudad>Knoxville</ciudad>
                    <cp>37919</cp>
                    <provincia>Tennessee</provincia>
                </direccion>
                <correo>iabarcae@yahoo.es</correo>
                <fecha_inclusion>08/07/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>03</id_pedido>
                    <fecha_compra>20/01/2021</fecha_compra>
                    <fecha_entrega>25/01/2021</fecha_entrega>
                    <total_factura>331,96€</total_factura>
                    <items>
                        <nombre>Kingston XS2000 Portable SSD 500GB USB 3.2</nombre>
                        <referencia>571836</referencia>
                        <precio>82,99€</precio>
                        <unidades>4</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Gay</nombre>
                <apellidos>Jeffels</apellidos>
                <tlf>336-486-7487</tlf>
                <direccion>
                    <calle>241 Moland Pass</calle>
                    <ciudad>Greensboro</ciudad>
                    <cp>27425</cp>
                    <provincia>North Carolina</provincia>
                </direccion>
                <correo>maeillanes@hotmail.com</correo>
                <fecha_inclusion>22/11/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>04</id_pedido>
                    <fecha_compra>02/02/2021</fecha_compra>
                    <fecha_entrega>10/02/2021</fecha_entrega>
                    <total_factura>259€</total_factura>
                    <items>
                        <nombre>Samsung Galaxy Watch4 4G 44mm Plata</nombre>
                        <referencia>478835</referencia>
                        <precio>259€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Gay</nombre>
                <apellidos>Jeffels</apellidos>
                <tlf>336-486-7487</tlf>
                <direccion>
                    <calle>241 Moland Pass</calle>
                    <ciudad>Greensboro</ciudad>
                    <cp>27425</cp>
                    <provincia>North Carolina</provincia>
                </direccion>
                <correo>maeillanes@hotmail.com</correo>
                <fecha_inclusion>22/11/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>05</id_pedido>
                    <fecha_compra>18/02/2021</fecha_compra>
                    <fecha_entrega>22/02/2021</fecha_entrega>
                    <total_factura>1019€</total_factura>
                    <items>
                        <nombre>Samsung Galaxy S23 256GB Verde Libre + Cargador 25W</nombre>
                        <referencia>10661574</referencia>
                        <precio>1019€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Lewes</nombre>
                <apellidos>Whittick</apellidos>
                <tlf>615-457-8338</tlf>
                <direccion>
                    <calle>1 Hagan Alley</calle>
                    <ciudad>Nashville</ciudad>
                    <cp>37220</cp>
                    <provincia>Tennessee</provincia>
                </direccion>
                <correo>lwhittickg@hotmail.com</correo>
                <fecha_inclusion>10/01/2021</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>06</id_pedido>
                    <fecha_compra>24/02/2021</fecha_compra>
                    <fecha_entrega>28/02/2021</fecha_entrega>
                    <total_factura>721,99€</total_factura>
                    <items>
                        <nombre>Candy CCVB 60D/1 DiVino Vinoteca 38 Botellas</nombre>
                        <referencia>587072</referencia>
                        <precio>721,99€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Frasco</nombre>
                <apellidos>De Michetti</apellidos>
                <tlf>508-758-6056</tlf>
                <direccion>
                    <calle>00 Dapin Trail</calle>
                    <ciudad>Brockton</ciudad>
                    <cp>2305</cp>
                    <provincia>Massachusetts</provincia>
                </direccion>
                <correo>fdemichettih@gmail.com</correo>
                <fecha_inclusion>20/01/2021</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>07</id_pedido>
                    <fecha_compra>27/02/2021</fecha_compra>
                    <fecha_entrega>01/03/2021</fecha_entrega>
                    <total_factura>91,98€</total_factura>
                    <items>
                        <nombre>MSI Vigor GK50 Low Profile TKL Teclado Gaming Negro</nombre>
                        <referencia>10026475</referencia>
                        <precio>91,98€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Maud</nombre>
                <apellidos>Lively</apellidos>
                <tlf>231-953-2541</tlf>
                <direccion>
                    <calle>85797 Rieder Alley</calle>
                    <ciudad>Muskegon</ciudad>
                    <cp>49444</cp>
                    <provincia>Michigan</provincia>
                </direccion>
                <correo>mlivelyi@yahoo.es</correo>
                <fecha_inclusion>24/02/2021</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>08</id_pedido>
                    <fecha_compra>01/03/2021</fecha_compra>
                    <fecha_entrega>05/03/2021</fecha_entrega>
                    <total_factura>962,36€</total_factura>
                    <items>
                        <nombre>Canon EOS 2000D 24.1MP WiFi + EF-S 18-55mm F3.5-5.6 IS III</nombre>
                        <referencia>260062</referencia>
                        <precio>481,18€</precio>
                        <unidades>2</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Clarice</nombre>
                <apellidos>Austins</apellidos>
                <tlf>602-320-8648</tlf>
                <direccion>
                    <calle>933 Lunder Road</calle>
                    <ciudad>Phoenix</ciudad>
                    <cp>85030</cp>
                    <provincia>Arizona</provincia>
                </direccion>
                <correo>caustinsj@gmail.com</correo>
                <fecha_inclusion>24/02/2021</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>09</id_pedido>
                    <fecha_compra>01/03/2021</fecha_compra>
                    <fecha_entrega>05/03/2021</fecha_entrega>
                    <total_factura>206,97€</total_factura>
                    <items>
                        <nombre>Corsair Vengeance RGB Pro DDR4 3200 PC4-25600 16GB 2x8GB CL16</nombre>
                        <referencia>164467</referencia>
                        <precio>68,99€</precio>
                        <unidades>3</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Georgie</nombre>
                <apellidos>Mapples</apellidos>
                <tlf>402-950-5930</tlf>
                <direccion>
                    <calle>0 Doe Crossing Hill</calle>
                    <ciudad>Omaha</ciudad>
                    <cp>68179</cp>
                    <provincia>Nebraska</provincia>
                </direccion>
                <correo>gmapplesk@gmail.com</correo>
                <fecha_inclusion>28/02/2021</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>10</id_pedido>
                    <fecha_compra>10/03/2021</fecha_compra>
                    <fecha_entrega>17/03/2021</fecha_entrega>
                    <total_factura>99,5€</total_factura>
                    <items>
                        <nombre>Unotec Hub 7x USB 2.0 Negro</nombre>
                        <referencia>89706</referencia>
                        <precio>9,95€</precio>
                        <unidades>10</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
        </trimestre>
        <trimestre t="2">
            <cliente>
                <nombre>Kara</nombre>
                <apellidos>Roose</apellidos>
                <tlf>865-212-0796</tlf>
                <direccion>
                    <calle>13779 Crescent Oaks Terrace</calle>
                    <ciudad>Knoxville</ciudad>
                    <cp>37919</cp>
                    <provincia>Tennessee</provincia>
                </direccion>
                <correo>iabarcae@yahoo.es</correo>
                <fecha_inclusion>08/07/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>11</id_pedido>
                    <fecha_compra>05/04/2021</fecha_compra>
                    <fecha_entrega>10/04/2021</fecha_entrega>
                    <total_factura>82,98€</total_factura>
                    <items>
                        <nombre>Canon PIXMA TS705a Impresora Color WiFi Dúplex</nombre>
                        <referencia>10430155</referencia>
                        <precio>82,98€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Kara</nombre>
                <apellidos>Roose</apellidos>
                <tlf>865-212-0796</tlf>
                <direccion>
                    <calle>13779 Crescent Oaks Terrace</calle>
                    <ciudad>Knoxville</ciudad>
                    <cp>37919</cp>
                    <provincia>Tennessee</provincia>
                </direccion>
                <correo>iabarcae@yahoo.es</correo>
                <fecha_inclusion>08/07/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>12</id_pedido>
                    <fecha_compra>12/04/2021</fecha_compra>
                    <fecha_entrega>18/04/2021</fecha_entrega>
                    <total_factura>94,94€</total_factura>
                    <items>
                        <nombre>TP-Link Deco M4 Sistema WiFi Mesh AC1200 Dual Band Gigabit Pack 2</nombre>
                        <referencia>196765</referencia>
                        <precio>94,94€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Kara</nombre>
                <apellidos>Roose</apellidos>
                <tlf>865-212-0796</tlf>
                <direccion>
                    <calle>13779 Crescent Oaks Terrace</calle>
                    <ciudad>Knoxville</ciudad>
                    <cp>37919</cp>
                    <provincia>Tennessee</provincia>
                </direccion>
                <correo>iabarcae@yahoo.es</correo>
                <fecha_inclusion>08/07/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>13</id_pedido>
                    <fecha_compra>15/24/2021</fecha_compra>
                    <fecha_entrega>20/04/2021</fecha_entrega>
                    <total_factura>125,34€</total_factura>
                    <items>
                        <nombre>HP Laserjet M110w Impresora Láser Monocromo WiFi</nombre>
                        <referencia>10108280</referencia>
                        <precio>125,34€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Gay</nombre>
                <apellidos>Jeffels</apellidos>
                <tlf>336-486-7487</tlf>
                <direccion>
                    <calle>241 Moland Pass</calle>
                    <ciudad>Greensboro</ciudad>
                    <cp>27425</cp>
                    <provincia>North Carolina</provincia>
                </direccion>
                <correo>maeillanes@hotmail.com</correo>
                <fecha_inclusion>22/11/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>14</id_pedido>
                    <fecha_compra>20/04/2021</fecha_compra>
                    <fecha_entrega>25/04/2021</fecha_entrega>
                    <total_factura>969€</total_factura>
                    <items>
                        <nombre>HP Victus 16-d1033ns Intel Core i7-12700H/16GB/512GB SSD/RTX 3060/16.1''</nombre>
                        <referencia>10370447</referencia>
                        <precio>969€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Gay</nombre>
                <apellidos>Jeffels</apellidos>
                <tlf>336-486-7487</tlf>
                <direccion>
                    <calle>241 Moland Pass</calle>
                    <ciudad>Greensboro</ciudad>
                    <cp>27425</cp>
                    <provincia>North Carolina</provincia>
                </direccion>
                <correo>maeillanes@hotmail.com</correo>
                <fecha_inclusion>22/11/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>15</id_pedido>
                    <fecha_compra>24/04/2021</fecha_compra>
                    <fecha_entrega>29/04/2021</fecha_entrega>
                    <total_factura>3099€</total_factura>
                    <items>
                        <nombre>LG OLED77C24LA 77" OLED 4K HDR10 Pro</nombre>
                        <referencia>10241193</referencia>
                        <precio>3099€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Raynell</nombre>
                <apellidos>Sanzio</apellidos>
                <tlf>408-958-8065</tlf>
                <direccion>
                    <calle>41 Fulton Pass</calle>
                    <ciudad>Sunnyvale</ciudad>
                    <cp>94089</cp>
                    <provincia>California</provincia>
                </direccion>
                <correo>rsanziol@yahoo.es</correo>
                <fecha_inclusion>24/04/2021</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>16</id_pedido>
                    <fecha_compra>29/04/2021</fecha_compra>
                    <fecha_entrega>03/05/2021</fecha_entrega>
                    <total_factura>222,24€</total_factura>
                    <items>
                        <nombre>Huawei MatePad T 10s 10.1" 3/64GB Wifi Azul</nombre>
                        <referencia>317822</referencia>
                        <precio>222,24€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Sharon</nombre>
                <apellidos>Hylton</apellidos>
                <tlf>602-538-0817</tlf>
                <direccion>
                    <calle>1134 Morrow Center</calle>
                    <ciudad>Phoenix</ciudad>
                    <cp>85083</cp>
                    <provincia>Arizona</provincia>
                </direccion>
                <correo>shyltonm@gmail.com</correo>
                <fecha_inclusion>01/04/2021</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>17</id_pedido>
                    <fecha_compra>02/05/2021</fecha_compra>
                    <fecha_entrega>08/04/2021</fecha_entrega>
                    <total_factura>1.830€</total_factura>
                    <items>
                        <nombre>Optoma UHD35x Proyector DLP 3D UltraHD 4K 3.600 Lúmenes</nombre>
                        <referencia>10622235</referencia>
                        <precio>915€</precio>
                        <unidades>2</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Sydney</nombre>
                <apellidos>Heditch</apellidos>
                <tlf>734-554-4189</tlf>
                <direccion>
                    <calle>601 Nelson Lane</calle>
                    <ciudad>Detroit</ciudad>
                    <cp>48258</cp>
                    <provincia>Michigan</provincia>
                </direccion>
                <correo>sheditchn@gmail.com</correo>
                <fecha_inclusion>04/04/2021</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>18</id_pedido>
                    <fecha_compra>12/04/2021</fecha_compra>
                    <fecha_entrega>18/04/2021</fecha_entrega>
                    <total_factura>999€</total_factura>
                    <items>
                        <nombre>Acer Predator Triton 300 PT315-53-74QS Intel Core i7-11800H/16GB/1TB SSD/RTX 3050Ti/15.6"</nombre>
                        <referencia>10649520</referencia>
                        <precio>999€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Xylia</nombre>
                <apellidos>Eton</apellidos>
                <tlf>630-640-5019</tlf>
                <direccion>
                    <calle>82531 Mitchell Park</calle>
                    <ciudad>Chicago</ciudad>
                    <cp>60604</cp>
                    <provincia>Illinois</provincia>
                </direccion>
                <correo>xetono@naver.com</correo>
                <fecha_inclusion>08/04/2021</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>19</id_pedido>
                    <fecha_compra>20/04/2021</fecha_compra>
                    <fecha_entrega>28/04/2021</fecha_entrega>
                    <total_factura>445,86€</total_factura>
                    <items>
                        <nombre>Canon Objetivo EF 50mm f/1.8 STM</nombre>
                        <referencia>83207</referencia>
                        <precio>148,62€</precio>
                        <unidades>3</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Neysa</nombre>
                <apellidos>Raw</apellidos>
                <tlf>339-467-7704</tlf>
                <direccion>
                    <calle>0 Vermont Lane</calle>
                    <ciudad>Woburn</ciudad>
                    <cp>1813</cp>
                    <provincia>Massachusetts</provincia>
                </direccion>
                <correo>nrawp@gmail.com</correo>
                <fecha_inclusion>10/04/2021</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>20</id_pedido>
                    <fecha_compra>10/05/2021</fecha_compra>
                    <fecha_entrega>20/05/2021</fecha_entrega>
                    <total_factura>227,96€</total_factura>
                    <items>
                        <nombre>Kingston FURY Beast RGB DDR4 3200 MHz 16GB 2x8GB CL16</nombre>
                        <referencia>432765</referencia>
                        <precio>56,99€</precio>
                        <unidades>4</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
        </trimestre>
        <trimestre t="3">
            <cliente>
                <nombre>Kara</nombre>
                <apellidos>Roose</apellidos>
                <tlf>865-212-0796</tlf>
                <direccion>
                    <calle>13779 Crescent Oaks Terrace</calle>
                    <ciudad>Knoxville</ciudad>
                    <cp>37919</cp>
                    <provincia>Tennessee</provincia>
                </direccion>
                <correo>iabarcae@yahoo.es</correo>
                <fecha_inclusion>08/07/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>21</id_pedido>
                    <fecha_compra>03/07/2021</fecha_compra>
                    <fecha_entrega>08/07/2021</fecha_entrega>
                    <total_factura>749€</total_factura>
                    <items>
                        <nombre>Apple iPad 2022 10.9" WiFi+Cellular 64GB Plata</nombre>
                        <referencia>10635701</referencia>
                        <precio>749€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Kara</nombre>
                <apellidos>Roose</apellidos>
                <tlf>865-212-0796</tlf>
                <direccion>
                    <calle>13779 Crescent Oaks Terrace</calle>
                    <ciudad>Knoxville</ciudad>
                    <cp>37919</cp>
                    <provincia>Tennessee</provincia>
                </direccion>
                <correo>iabarcae@yahoo.es</correo>
                <fecha_inclusion>08/07/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>22</id_pedido>
                    <fecha_compra>10/07/2021</fecha_compra>
                    <fecha_entrega>15/07/2021</fecha_entrega>
                    <total_factura>135€</total_factura>
                    <items>
                        <nombre>Apple Pencil 2a Generación para iPad Pro 2018</nombre>
                        <referencia>177200</referencia>
                        <precio>135€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Kara</nombre>
                <apellidos>Roose</apellidos>
                <tlf>865-212-0796</tlf>
                <direccion>
                    <calle>13779 Crescent Oaks Terrace</calle>
                    <ciudad>Knoxville</ciudad>
                    <cp>37919</cp>
                    <provincia>Tennessee</provincia>
                </direccion>
                <correo>iabarcae@yahoo.es</correo>
                <fecha_inclusion>08/07/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>23</id_pedido>
                    <fecha_compra>13/07/2021</fecha_compra>
                    <fecha_entrega>18/07/2021</fecha_entrega>
                    <total_factura>50€</total_factura>
                    <items>
                        <nombre>Apple Recambio Puntas Apple Pencil para iPad Pro</nombre>
                        <referencia>209757</referencia>
                        <precio>25€</precio>
                        <unidades>2</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Gay</nombre>
                <apellidos>Jeffels</apellidos>
                <tlf>336-486-7487</tlf>
                <direccion>
                    <calle>241 Moland Pass</calle>
                    <ciudad>Greensboro</ciudad>
                    <cp>27425</cp>
                    <provincia>North Carolina</provincia>
                </direccion>
                <correo>maeillanes@hotmail.com</correo>
                <fecha_inclusion>22/11/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>24</id_pedido>
                    <fecha_compra>20/07/2021</fecha_compra>
                    <fecha_entrega>26/07/2021</fecha_entrega>
                    <total_factura>349,94€</total_factura>
                    <items>
                        <nombre>Newskill Belenor PRO Mesa Gaming Negra Ajustable en Altura 120x60Cm</nombre>
                        <referencia>10640631</referencia>
                        <precio>349,94€</precio>
                        <unidades>1</unidades>
                    </items>
                </detalles_pedido>
            </cliente>
            <cliente>
                <nombre>Gay</nombre>
                <apellidos>Jeffels</apellidos>
                <tlf>336-486-7487</tlf>
                <direccion>
                    <calle>241 Moland Pass</calle>
                    <ciudad>Greensboro</ciudad>
                    <cp>27425</cp>
                    <provincia>North Carolina</provincia>
                </direccion>
                <correo>maeillanes@hotmail.com</correo>
                <fecha_inclusion>22/11/2020</fecha_inclusion>
                <detalles_pedido>
                    <id_pedido>25</id_pedido>
                    <fecha_compra>27/07/2021</fecha_compra>
                    <fecha_entrega>01/08/2021</fecha_entrega>
                    <total_factura>282,99€</total_factura>
                    <items>
                        <nombre>Newskill Kuraokami Negra/Blanca</nombre>
                        <referencia>126926</referencia>
                        <precio>282,99€</precio>
                        <unidades>1</unidades>